[package]
name = "macros"
version = "0.1.0"
authors = ["DanielGazit <danieligazit@gmail.com>"]

[lib]
crate_type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
syn = "1.0"

Inflector = "0.11"